version: '3.8'

services:
  service:
    build:
      context: app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app/static/:./app/static/:rw
    env_file:
      - .env
    

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - service
    env_file:
      - .env

volumes:
  postgres-data:
